### ISSUE TITLE
Cannot Compile with Angular 15

### ISSUE THREAD

**Issue by thunder033** [StefH/angular-odata-es5#142]
The `ODataServiceFactory` fails Angular 15 DI - basically makes the package unusable:

```
  NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
    This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

    Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.

      at ɵɵinvalidFactoryDep (../../node_modules/@angular/core/fesm2015/core.mjs:649:11)
      at Object.ODataServiceFactory_Factory [as factory] (../../ng:/ODataServiceFactory/ɵfac.js:5:47)

```

**Comment by StefH** [comment]
@thunder033 

Sorry, I cannot get it working anymore...

See also
https://github.com/StefH/angular-odata-es5/issues/122


If you can help?

**Comment by thunder033** [comment]
I was able to get it working by creating a wrapper class that compiles in the project with Angular 15:
```
@Injectable()
export class LegacyODataServiceFactory extends ODataServiceFactory {
  constructor(httpClient: HttpClient, oDataConfig: ODataConfiguration) {
    super(httpClient, oDataConfig);
  }
}
```

With a simple override:
```
{ provide: ODataServiceFactory, useClass: LegacyODataServiceFactory }
```

**Comment by StefH** [comment]
@thunder033 
Thanks for the update
